### ISSUE TITLE
How I fix this?

### ISSUE THREAD

**Issue by ghost** [Expectatives/Ticket-bot#1]
[FATAL] Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
      at WebSocketManager.createShards (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:245:15)
      at async Client.login (/home/container/node_modules/discord.js/src/client/Client.js:254:7) {
    [Symbol(code)]: 'DISALLOWED_INTENTS'
  }
}  reason:  Privileged intent provided is not enabled or whitelisted.

**Comment by devdeem** [comment]
You have to enable in the [Discord Developer Portal](https://discord.com/developers/applications) intent that you use in the code when you define the client
